version: '3.7'
services:
  nodejs-api:
    build:
      context: ./server/
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    container_name: nodejs-api
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
  react-client: 
    build:
      context: ./dev-ops-app/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    container_name: react-client
